
# html lang
language: zh-cn

# main menu navigation
menu:
  Home: /
  Search: /search
  Archives: /archives
  RSS: /rss
  About: /about

# stylesheets loaded in the <head>
stylesheets:
- /css/hexo-theme-nothin-here.css
- /css/highlight-nothin-here.css
- https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&icon_names=arrow_back,arrow_forward,inbox_text,info,rss_feed,search

# scripts loaded in the end of the body
scripts:
- /js/hexo-theme-nothin-here.js

# default thumbnail
default_thumbnail:
- /assets/banner.png
